services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ~/volumes/airbnb/postgresql/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=root
    ports:
      - 127.0.0.1:5433:5432
